# https://gist.github.com/joaosalless/dbc295c5f8954747ee7dae92e466fb35
# https://stackoverflow.com/questions/11117823/git-push-error-refusing-to-update-checked-out-branch
name: Deploy to HostGator Main

on:
  pull_request:
    branches:
      - main
    types: [ closed ]

jobs:
  deploy:
    timeout-minutes: 3
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      EMAIL: ${{ secrets.EMAIL }}
      GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock

    strategy:
      matrix:
        node-version: [ '18.x' ]

    steps:
      - uses: actions/checkout@v4

#      - name: Dump GitHub context
#        env:
#          GITHUB_CONTEXT: ${{ toJSON(github) }}
#        run: |
#          # echo "$GITHUB_CONTEXT"

      - name: SSH Setup
        run: |
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" > ~/.ssh/config
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Setup Git
        run: |
          git config --global user.email "$EMAIL"
          git config --global user.name "$GIT_USERNAME"
          echo git remote -v

      - name: Deploy to Hostgator
        run: |
          git remote add hostgator "${{ secrets.MAIN_ADDRESS }}"
          git fetch --unshallow
          git push -u hostgator "${{ secrets.MAIN_BRANCH }}"
